name: Haskell CI

on:
  push:
    branches: [ main, 'feature_*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.2'
        cabal-version: '3.8'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build and Install
      run: |
        cabal build --enable-tests --enable-benchmarks all
        cabal install --overwrite-policy=always
    - name: Install shelltestrunner
      run: cabal install shelltestrunner --overwrite-policy=always
    - name: Run tests
      run: |
        cabal test all
        PATH=~/.cabal/bin/:PATH shelltest --execdir tests/paycheck_import -a
